### ISSUE TITLE
Falling through maps with resize mutator

### ISSUE THREAD

**Issue by thomorl** [redeclipse/base#1048]
When playing the map "Trespass" with the `resize` mutator, it is very common for players to fall through the floor of the map upon respawn.

- Version and build: [`v2.0.0`] [`2978`]
- How to reproduce: Play "Trespass" with the `resize` mutator, get killed and respawn (bug occurs very often, although not consistently).

**Comment by Jigoku** [comment]
Seems so yeah. I can confirm this happens on both 2.0 and master branch.
Just noticed it still occasionally happens on other maps too.

**Comment by qreeves** [comment]
Woops, wrong button sorry.

**Comment by dc-de** [comment]
I think this can be closed because the the bug with spawn size positions in resize mode is fixed in 2.0.1

**Comment by Jigoku** [comment]
> I think this can be closed because the the bug with spawn size positions in resize mode is fixed in 2.0.1

It's still happening, just checked. I don't think there were any changes made relating to this issue since the previous comments.

If you load up resize on any map, it happens randomly when spawning.
